### ISSUE TITLE
Quick start tutorial fails @ step 3

### ISSUE THREAD

**Issue by azzaea** [intervene-EU-H2020/synthetic_data#22]
Hello,

Thank you for providing this tool. I'm trying to run it in a cluster, and running into an issue in step 3:
```
hapnest$ singularity exec --bind data/:/data/ --env JULIA_DEPOT_PATH=/home/p287664/tmp/.julia containers/intervene-synthetic-data_latest.sif init
  Installing known registries into `~/tmp/.julia`
ERROR: ArgumentError: "/local/tmp" is not a directory
Stacktrace:
  [1] tempname(parent::String; cleanup::Bool)
    @ Base.Filesystem ./file.jl:580
  [2] tempname (repeats 2 times)
    @ ./file.jl:580 [inlined]
  [3] pkg_server_registry_urls()
    @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:991
  [4] clone_default_registries(ctx::Pkg.Types.Context; only_if_empty::Bool)
    @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:914
  [5] clone_default_registries
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:908 [inlined]
  [6] find_registered!(ctx::Pkg.Types.Context, names::Vector{String}, uuids::Vector{Base.UUID})
    @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1291
  [7] find_registered!
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1252 [inlined]
  [8] check_registered(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1155
  [9] instantiate(ctx::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Base.BinaryPlatforms.Platform, allow_build::Bool, allow_autoprecomp::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1366
 [10] instantiate
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1325 [inlined]
 [11] #instantiate#252
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1321 [inlined]
 [12] instantiate()
    @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1321
 [13] top-level scope
    @ none:1

```

I suspect the image expects `/local/tmp` to be writable on the machine itself. Is this correct? How can I correct for this?

Thank you again,
Azza

**Comment by v-i-s-h** [comment]
Hi,
Thanks for raising this issue. Could you please verify whether the path `\local\tmp\` exists? I suspect this may be due to `tmp` directory not existing.

Also, it seems like even though you use `/home/<>/tmp/.julia` in your commandline, it is getting redirected to `\local\tmp`. Is this expected? You may want to use `~/.julia` as `JULIA_DEPOT_PATH`.

**Comment by azzaea** [comment]
Hello,
Thank you for the quick response. 
* `/local/tmp` exists:
```
p287664@peregrine hapnest$ ll -htr /local/
total 2.4M
drwx------.    2 root root  16K Sep 27  2017 lost+found
drwxr-xr-x.    3 root root 4.0K Sep 29  2017 cvmfs
drwxrwxrwt. 1488 root root 2.3M Feb  6 08:21 tmp
```
* The redirection is strange. I can create files in `~` or `/home/<>/tmp/.julia` via touch command as normal:
```
p287664@peregrine hapnest$ touch /home/p287664/tmp/.julia/tst
p287664@peregrine hapnest$ tree /home/p287664/tmp/.julia/
/home/p287664/tmp/.julia/
├── logs
│   └── manifest_usage.toml
└── tst
```
* I tried the command with and without `--env JULIA_DEPOT_PATH=/home/p287664/tmp/.julia`, and the error (and logs) is similar. 
```
p287664@peregrine hapnest$cat ~/.julia/logs/manifest_usage.toml
[["/opt/intervene/scripts/Manifest.toml"]]
time = 2023-02-06T08:24:31.474Z
p287664@peregrine hapnest$
p287664@peregrine hapnest$
p287664@peregrine hapnest$ cat /home/p287664/tmp/.julia/logs/manifest_usage.toml 
[["/opt/intervene/scripts/Manifest.toml"]]
time = 2023-02-06T01:02:47.395Z
[["/opt/intervene/scripts/Manifest.toml"]]
time = 2023-02-06T01:03:25.454Z
[["/opt/intervene/scripts/Manifest.toml"]]
time = 2023-02-06T08:19:43.204Z
[["/opt/intervene/scripts/Manifest.toml"]]
time = 2023-02-06T08:27:06.343Z

```

**Comment by v-i-s-h** [comment]
Ok. This looks good. May be it is not redirecting at all - Julia Pkg is actually try to create a temporary directories for cloning registries. 
Can you test by adding `--env TMPDIR=/home/<>/tmp/` when starting the container? I suspect the call to [`tempname()`](https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.tempname) is getting some wrong directory information from [`tempdir()`](https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.tempdir). In `tempdir()` documentation, you can find that it looks for env variables - TMPDIR, TMP, TEMP, and TEMPDIR - to determine the temporary directory. May be one or more of this is pointing to `/local/tmp`.

If this is also failing, can you also report the current values for the these four environment variables?

On the other hand, your directory rights flags for `/local/tmp` seems valid for me - you must be able to write into it. A possible reason could be `/local/tmp/` here may be referring to the path inside container. But this needs more investigation.

**Comment by azzaea** [comment]
Excellent! You were correct, `TMPDIR` points to `/local/tmp`, so setting it as you suggested solved the error.
